### PR TITLE
Ss4 upgrade

### PR DESCRIPTION
**Pull request by priyashantha**

### CODE REVIEW

**Comment by Cheddam** [comment]
Thanks @priyashantha! I'm going to do some additional tidying before pushing this to master and tagging a release, so I've changed the base branch.

**Comment by priyashantha** [comment]
@Cheddam Thanks for checking and merging.

**Comment by priyashantha** [comment]
@Cheddam It looks we can't still use `dev-ss4-upgrade` with composer without our vcs. Could you please check this for me?

I tried with `composer require edgarindustries/youtubefield dev-ss4-upgrade` and `composer require silverstripe-rebelalliance/youtubefield dev-ss4-upgrade`

I can see there are 2 different vendors in master and ss4-upgrade branches

**Comment by edlinklater** [comment]
@priyashantha The project has now been re-submitted to Packagist as `edgarindustries/youtubefield`, so you should be able to use the SS4 version without `vcs` defined.

**Comment by priyashantha** [comment]
@edlinklater Thank you very much for letting me know.

**Pull request merged**
